### PR TITLE
Added basic modal module

### PR DESCRIPTION
**Pull request by bnhovde**
@davislurve @chris-pearce 

I've just added a basic starter module for the modal.

I've opted to make it a factory function, classless and use the revealing module pattern.

All of these things are up for debate. I'm just chucking some wood on the fire really ;)

ps: There's no accessibility code added yet. Feel free to add this.

### CODE REVIEW

**Comment by bnhovde** [comment]
PS: I'm happy to go down the class route, but all that Eric Elliott propaganda is getting to me. Up to you guys!

**Comment by DaveOrDead** [comment]
Haha, nah I'm with you on the classless stuff.  Looks like a good approach.

**Comment by DaveOrDead** [comment]
LGTM

**Comment by chris-pearce** [comment]
LGTM too, I went through it with @davislurve earlier to be clear on the architecture of a module and all makes sense :+1:.

**Pull request merged**
